tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "asciiquarium"
brew "bat"
brew "docker"
brew "docker-compose"
brew "libpq"
brew "lsd"
brew "neofetch"
brew "nvm"
brew "postgresql"
brew "terraform"

cask "font-fira-code"
