typeset -U PATH

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export EDITOR="nvim"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export DOTFILES_DIR="$HOME/projects/dotfiles"

export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/.zcompdump-${HOST/.*/}-${ZSH_VERSION}"
export HISTFILE="$XDG_CACHE_HOME/zsh/zsh_history"
export ZSH="$XDG_CONFIG_HOME/oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"

export PATH="$DOTFILES_DIR/bin:$HOME/bin:/usr/local/bin:/usr/local/opt/openjdk/bin:$PATH"

export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

eval "$(/opt/homebrew/bin/brew shellenv)"

export NVM_DIR="$XDG_CONFIG_HOME/nvm"

CASE_SENSTIVE="true"
ZSH_THEME="powerlevel10k/powerlevel10k"
source $DOTFILES_DIR/zsh/p10k.zsh
source $ZSH/oh-my-zsh.sh

zstyle ':omz:plugins:nvm' lazy yes
plugins=(nvm)

alias flush-branches="git branch --merged main | grep -v 'main' | xargs git branch -d && git remote prune origin"
alias ll="lsd -la"
alias pu="nvim +PlugUpdate +qa"
alias pull="git pull && flush-branches"
alias vi="nvim"
alias vim="nvim"
alias ws="python3 -m http.server"
alias docker-purge="docker system prune -fa --volumes"
alias python="python3"

mc(){ mkdir "$1" && cd "$1" ; }
